apiVersion: v1
kind: Service
metadata:
  labels:
    app: host-path
  name: newnode
  namespace: flux-system
spec:
  ports:
  - port: 82
    protocol: TCP
    targetPort: 80
  selector:
      app: my-dp
  type: NodePort

